### ISSUE TITLE
:wrench: Get rid of husky

### ISSUE THREAD

**Issue by nelkor** [nelkor/passcryptum#50]
We tried husky for pre-commit hooks. It turned out to be pretty useless. Its functionality boils down to executing some commands before committing. But at the same time, it is still possible to commit any code that bypasses husky. That is, the code in the PR still needs to be rechecked (husky does not give any guarantees). And when committing, husky forces us to run tests and linters every time, even if we only run them manually (and wastes our time).

Conclusion: we tried and made sure that we do not need husky. We must get rid of him.

**Comment by antongospod** [comment]
You might look in the direction of the lint-staged library. Below is a sample configuration in package.json
```
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.{js,vue}": [
      "prettier --write",
      "eslint --fix"
    ],
    "*.{vue,scss,css}": [
      "prettier --write"
    ]
  },
```

**Comment by nelkor** [comment]
The problem I see with the precommit hooks is this. The only normal development process is to first make sure that your code is good enough, and only then commit. If the programmer checks the validity of the code by trying to commit, then this is wrong. All precommit hooks do is make us wait for commands to execute.

At the same time, precommit hooks cannot even guarantee us that there will be no invalid code in the PR. Because they can be bypassed.

**Comment by antongospod** [comment]
I think it is the developer's job to check the validity of the code and to lint it in a timely fashion. If you are working through PL, you can set up a Github Actions workflow so that tests and linter are run when the PL is created. If any of the pipelines are down, then block the merge. With this approach, if the pipelines fail, the developer should run the linter, check that the tests work, commit, and then squash all their commits into one.

Furthermore, modern IDEs show almost all eslint|prettier|stylelint errors and you can fix most of them by using hotkeys or by setting up a linter run when saving.

![runLintOnSave](https://user-images.githubusercontent.com/47962758/230765858-5a37352d-020f-4a2a-9918-77e44377ad67.png)

**Comment by nelkor** [comment]
I don't know what "PL" is, do you mean "PR"?

Github Actions look great, but I've never set them up. What is needed for this? Could you do it? Are you interested in this app, btw?

**Comment by antongospod** [comment]
Yes, my mistake( I meant Pull Request.
I was looking for a convenient and simple password manager and I was interested in the stack you used and the architecture you chose. I could set up a CI.

**Comment by nelkor** [comment]
Great. How can I help you do this?

**Comment by antongospod** [comment]
Need a issue number to implement this feature

**Comment by nelkor** [comment]
@antongospod, #57 has been created for you. This issue remains to get rid of husky)
